# Generated by Django 4.2 on 2026-06-25 07:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_url', models.URLField(validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('duration', models.DurationField(help_text='Video duration in HH:MM:SS format.')),
                ('description', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson__course', 'lesson__order', 'id'],
            },
        ),
    ]
