# Generated by Django 4.2 on 2026-06-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videolesson",
            name="speaker",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="videolesson",
            name="thumbnail",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="videolesson",
            name="title",
            field=models.CharField(default="Untitled video", max_length=255),
        ),
        migrations.AddField(
            model_name="videolesson",
            name="video_id",
            field=models.CharField(default="", editable=False, max_length=32),
        ),
        migrations.CreateModel(
            name="VideoWatchProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("watched_seconds", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_progress",
                        to="videos.videolesson",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "video"],
            },
        ),
        migrations.AddConstraint(
            model_name="videowatchprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "video"), name="unique_student_video_progress"
            ),
        ),
    ]
