# Generated by Django 4.2 on 2026-06-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('category', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'verbose_name_plural': 'glossary terms',
                'ordering': ['term'],
            },
        ),
    ]
