import api from './api.js';

const unwrap = (response) => response.data.results || response.data;

export const lmsService = {
  courses: (params) => api.get('/courses/', { params }).then(unwrap),
  myCourses: () => api.get('/courses/my/').then((response) => response.data),
  course: (id) => api.get(`/courses/${id}/`).then((response) => response.data),
  universities: (params) => api.get('/universities/', { params }).then(unwrap),
  faculties: (params) => api.get('/faculties/', { params }).then(unwrap),
  departments: (params) => api.get('/departments/', { params }).then(unwrap),
  academicYears: (params) => api.get('/academic-years/', { params }).then(unwrap),
  semesters: (params) => api.get('/semesters/', { params }).then(unwrap),
  educationDirections: (params) => api.get('/education-directions/', { params }).then(unwrap),
  academicGroups: (params) => api.get('/academic-groups/', { params }).then(unwrap),
  enrollments: (params) => api.get('/course-enrollments/', { params }).then(unwrap),
  lessons: (params) => api.get('/lessons/', { params }).then(unwrap),
  lectures: (params) => api.get('/lecture-materials/', { params }).then(unwrap),
  practices: (params) => api.get('/practice-materials/', { params }).then(unwrap),
  videos: (params) => api.get('/videos/', { params }).then(unwrap),
  video: (id) => api.get(`/videos/${id}/`).then((response) => response.data),
  videoRelated: (id) => api.get(`/videos/${id}/related/`).then((response) => response.data),
  videoNavigation: (id) => api.get(`/videos/${id}/navigation/`).then((response) => response.data),
  videoWatchProgress: (id) => api.get(`/videos/${id}/watch-progress/`).then((response) => response.data),
  updateWatchProgress: (id, payload) => api.post(`/videos/${id}/watch-progress/`, payload).then((response) => response.data),
  quizzes: (params) => api.get('/quizzes/', { params }).then(unwrap),
  lecture: (id) => api.get(`/lecture-materials/${id}/`).then((response) => response.data),
  lectureNavigation: (id) => api.get(`/lecture-materials/${id}/navigation/`).then((response) => response.data),
  practice: (id) => api.get(`/practice-materials/${id}/`).then((response) => response.data),
  practiceFiles: (id) => api.get(`/practice-materials/${id}/files/`).then((response) => response.data),
  resources: (params) => api.get('/resources/', { params }).then(unwrap),
  glossary: (params) => api.get('/glossary/', { params }).then(unwrap),
  search: (q) => api.get('/search/', { params: { q } }).then((response) => response.data),
  progressSummary: (params) => api.get('/progress-summary/', { params }).then((response) => response.data),
  createLearningEvent: (payload) => api.post('/learning-events/', payload).then((response) => response.data),
  studentAnalytics: () => api.get('/analytics/student/').then((response) => response.data),
  teacherAnalytics: () => api.get('/analytics/teacher/').then((response) => response.data),
  pdfProgress: (params) => api.get('/pdf-progress/', { params }).then(unwrap),
  savePdfProgress: (payload) => api.post('/pdf-progress/', payload).then((response) => response.data),
  updatePdfProgress: (id, payload) => api.patch(`/pdf-progress/${id}/`, payload).then((response) => response.data),
  notes: (params) => api.get('/notes/', { params }).then(unwrap),
  createNote: (payload) => api.post('/notes/', payload).then((response) => response.data),
  updateNote: (id, payload) => api.patch(`/notes/${id}/`, payload).then((response) => response.data),
  deleteNote: (id) => api.delete(`/notes/${id}/`),
  bookmarks: (params) => api.get('/bookmarks/', { params }).then(unwrap),
  createBookmark: (payload) => api.post('/bookmarks/', payload).then((response) => response.data),
  deleteBookmark: (id) => api.delete(`/bookmarks/${id}/`),
  certificates: (params) => api.get('/certificates/', { params }).then(unwrap),
  issueCertificate: (course) => api.post('/certificates/issue/', { course }).then((response) => response.data),
  notifications: (params) => api.get('/notifications/', { params }).then(unwrap),
  markNotificationRead: (id) => api.post(`/notifications/${id}/mark-read/`).then((response) => response.data),
};
