# Generated by Django 4.2 on 2026-06-25 07:52

import apps.materials.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(upload_to='materials/practices/', validators=[apps.materials.validators.validate_pdf_file])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_materials', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson__course', 'lesson__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(upload_to='materials/lectures/', validators=[apps.materials.validators.validate_pdf_file])),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_materials', to='lessons.lesson')),
            ],
            options={
                'ordering': ['lesson__course', 'lesson__order', 'id'],
            },
        ),
    ]
