# Generated by Django 4.2 on 2026-06-25 08:06

import apps.materials.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
        ("courses", "0001_initial"),
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("books", "Books"),
                            ("articles", "Articles"),
                            ("datasets", "Datasets"),
                            ("code", "Code"),
                            ("presentation", "Presentation"),
                            ("assignment", "Assignment"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="resources/",
                        validators=[apps.materials.validators.validate_resource_file],
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "title"],
            },
        ),
        migrations.AlterModelOptions(
            name="lecturematerial",
            options={"ordering": ["lesson__course", "lecture_number"]},
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="materials/lecture-covers/"
            ),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="estimated_reading_time",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Estimated reading time in minutes."
            ),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="lecture_number",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="title",
            field=models.CharField(default="Untitled lecture", max_length=255),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="estimated_time",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Estimated completion time in minutes."
            ),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="example_files",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="materials/practice-examples/",
                validators=[apps.materials.validators.validate_archive_file],
            ),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="source_code_files",
            field=models.FileField(
                blank=True, null=True, upload_to="materials/practice-code/"
            ),
        ),
        migrations.AddField(
            model_name="practicematerial",
            name="title",
            field=models.CharField(default="Untitled practice", max_length=255),
        ),
        migrations.AddField(
            model_name="resource",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="lessons.lesson",
            ),
        ),
    ]
